In [1]:
import pandas as pd

In [2]:
data = pd.read_excel(r'India-Corona.xlsx')
data

Week  Week.1  Total Cases  Deceased  Recovered
0 2022-03-01       1          396         7          1
1 2005-04-01       2         4289       118         99
2 2012-04-01       3         9205       331        111
3 2019-04-01       4        17615       559        391
4 2026-04-01       5        27890       881        584
5 2003-05-01       6        42505      1391        956

In [3]:
data.columns

Index(['Week', 'Week.1', 'Total Cases', 'Deceased', 'Recovered'], dtype='object')

In [4]:
data2 = data.iloc[:,[1,2]]
data2

Week.1  Total Cases
0       1          396
1       2         4289
2       3         9205
3       4        17615
4       5        27890
5       6        42505

In [5]:
data2.describe()

Week.1   Total Cases
count  6.000000      6.000000
mean   3.500000  16983.333333
std    1.870829  15921.671051
min    1.000000    396.000000
25%    2.250000   5518.000000
50%    3.500000  13410.000000
75%    4.750000  25321.250000
max    6.000000  42505.000000

In [6]:
data.shape

(6, 5)

In [7]:
data.count()

Week           6
Week.1         6
Total Cases    6
Deceased       6
Recovered      6
dtype: int64

In [8]:
data.columns

Index(['Week', 'Week.1', 'Total Cases', 'Deceased', 'Recovered'], dtype='object')

# Input as X

In [9]:
X = data2[["Week.1"]]
X

Week.1
0       1
1       2
2       3
3       4
4       5
5       6

In [10]:
type(X)

pandas.core.frame.DataFrame

# output as  Y

In [11]:
Y = data[['Total Cases']]
Y.values

array([[  396],
       [ 4289],
       [ 9205],
       [17615],
       [27890],
       [42505]])

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X.values,Y.values) # input , output

In [13]:
X_train

array([[4],
       [3],
       [6],
       [2]])

In [14]:
Y_train

array([[17615],
       [ 9205],
       [42505],
       [ 4289]])

In [15]:
X_test

array([[5],
       [1]])

In [16]:
Y_test

array([[27890],
       [  396]])

In [17]:
from sklearn.linear_model import LinearRegression
# object creation
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [18]:
Y_pred= model.predict(X_test)
Y_pred

array([[30636.42857143],
       [-8508.94285714]])

In [19]:
# bias
# Actual - Predicted
17615 - 22907

-5292

In [20]:
X_test

array([[5],
       [1]])

In [21]:
Y_test

array([[27890],
       [  396]])

In [22]:
model.predict([[5]])

array([[30636.42857143]])

In [23]:
model.predict([[10]])

array([[79568.14285714]])

# Metrics for Regression

In [32]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,explained_variance_score, max_error,median_absolute_error

In [33]:
mean_squared_error(Y_test,Y_pred)

43420438.59346941

In [34]:
mean_absolute_error(Y_test,Y_pred)

5825.685714285716

In [35]:
explained_variance_score(Y_test,Y_pred)

0.8204116180265782

In [36]:
median_absolute_error(Y_test,Y_pred)

np.float64(5825.685714285716)

In [37]:
from sklearn import metrics
metrics.r2_score(Y_test,Y_pred)

0.7702379271583726

In [38]:
model.coef_

array([[9786.34285714]])

In [39]:
model.score(X_train,Y_train)

0.968421365485141

In [40]:
model.intercept_

array([-18295.28571429])